sudo: false

language: node_js
node_js:
  - 12.16.1

branches:
  only:
    - master

deploy:
  provider: heroku
  app: "counting-backend-api"
  api_key:
    secure: "travis encrypt $(heroku auth:token) --add deploy.api_key --pro

after_success:
  - cat ./coverage/lcov.info | ./node_modules/codecov.io/bin/codecov.io.js
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
